# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-03 12:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catering', '0002_auto_20191003_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='user_name',
            new_name='usr_name',
        ),
    ]
